server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k6b203.p.ssafy.io:3306/alta?serverTimezone=Asia/Seoul
    username: k6b203
    password: k6b203ALTA@@

  redis:
    host: k6b203.p.ssafy.io
    port: 6379
    password: k6b203ALTA@@
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          github: # /oauth2/authorization/github 이 주소를 동작하게 한다.
            client-id: 3c388f133d2216e06569 #local :seoha test
            client-secret: b9d3c97ca3cdd536d733129fc193cf63d39e0680
#            client-id: d48d2214b6bcdcd5ec62
#            client-secret: b9aa9c706cab627a05d19abe6695c3332c46c800
            scope:
              - repo
              - user
jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 604800 #3600 : 1hour #604800 : 1 wee; #60 1mit
  refresh-token-validity-in-seconds: 604800
  url: http://k6b203.p.ssafy.io:80/auth


github:
  username: ssafytest001
  secret: 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
  reponame: test
  oauth-key : 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


